### ISSUE TITLE
Метод не суммирует время проигранное в игры определенного жанра игроком, выводится  ноль

### ISSUE THREAD

**Issue by birdperson913** [idsaidov/javaqa-team-project#1]
# Описание 
Если указанно количество проигранных часов, метод не суммирует время , результат всегда 0.

# Локация дефекта
https://github.com/idsaidov/javaqa-team-project/blob/b67ee0839d1e90ccd4b5572b7047f68cd794f6d9/src/main/java/ru/netology/Player.java#L45-L55

# Шаги воспроизведения
1. Открыть код программы в IDEA
1. Запустить тест  метода sumGenre , с данными проигранных часов 5 
1. Посмотреть вывод программы

*Ожидаемый результат - программа суммирует время проигранное игроком в игры одного жанра
*Фактический результат - ответ всегда ноль.

# Скриншот
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/81969845/193309401-46a6eaff-7228-4636-9bc6-33a2a8ec832d.png">

# Окружение:
* **операционная система:**  MacOS Monterey
* **IDE:** IntelliJ IDEA 2022.2.1 (Ultimate Edition)
* **Java:** OpenJDK 11

**Comment by idsaidov** [comment]
Исправил ошибку в коде метода play, метод возвращал количество часов, проведенное в игру. 
Метод sumGenere исправил, тест проходит.
Метод:
![Метод_1](https://user-images.githubusercontent.com/107353865/194123614-b150c0fa-7310-4eae-8742-b16dfcdddc55.png)
Тест:
![Тест_1](https://user-images.githubusercontent.com/107353865/194123657-a8dfe763-68a7-46af-bbe6-5e1c7faf0994.png)
