### ISSUE TITLE
При добавлении жанра игры в которую играли больше всего, метод всегда возвращает null 

### ISSUE THREAD

**Issue by birdperson913** [idsaidov/javaqa-team-project#2]
# Описание 
Метод не возвращает жанр в который играли больше всего, ответ всегда null, метод не реализован.

# Локация дефекта
https://github.com/idsaidov/javaqa-team-project/blob/b67ee0839d1e90ccd4b5572b7047f68cd794f6d9/src/main/java/ru/netology/Player.java#L59-L61

# Шаги воспроизведения
1. Открыть код из локации дефекта.
1. Убедиться что в выводе  null

*Ожидаемый результат:* Программа суммирует время проигранное игроком в игры одного жанра
*Фактический результат:* Ответ всегда ноль.

# Скриншот
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/81969845/193310954-5e7bd44d-c2ab-44ab-8fb3-baa73328ad42.png">

<img width="950" alt="image" src="https://user-images.githubusercontent.com/81969845/193311244-23d03361-648a-491c-9c61-670093af3167.png">

# Окружение:
* **операционная система:**  MacOS Monterey
* **IDE:** IntelliJ IDEA 2022.2.1 (Ultimate Edition)
* **Java:** OpenJDK 11

**Comment by idsaidov** [comment]
Прописал код в метод mostPlayerByGenre и внес правку в код теста shouldMostPlayerByGenre. Тест проходит.

Метод:
![Метод_3](https://user-images.githubusercontent.com/107353865/194126207-d9a56923-0c30-4ad9-85bb-518ff7e9e0d9.png)

Тест:
![Тест_3](https://user-images.githubusercontent.com/107353865/194126217-93fe019a-20ad-4f6a-bf3d-46992a9913f4.png)
