### ISSUE TITLE
не работает RunTimeException

### ISSUE THREAD

**Issue by birdperson913** [idsaidov/javaqa-team-project#3]
# Описание 
Метод не возвращает RunTimeException.

# Локация дефекта
https://github.com/idsaidov/javaqa-team-project/blob/b67ee0839d1e90ccd4b5572b7047f68cd794f6d9/src/main/java/ru/netology/Player.java#L28-L41

# Шаги воспроизведения
1. Открыть код программы в IDEA
1. Запустить тест RunTimeException
1. Посмотреть результат

*Ожидаемый результат:* Программа выдаст комментарий с класса RunTimeException
*Фактический результат:* Метод не реализован.

# Скриншот
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/81969845/193311963-2fd485c0-5272-4f77-a8e8-595305ad718b.png">
<img width="870" alt="image" src="https://user-images.githubusercontent.com/81969845/193312048-c6a9098f-94b4-427a-9970-5a01c59603fc.png">

# Окружение:
* **операционная система:**  MacOS Monterey
* **IDE:** IntelliJ IDEA 2022.2.1 (Ultimate Edition)
* **Java:** OpenJDK 11

**Comment by idsaidov** [comment]
Внес правки в код . Тест проходит

Метод:
![Метод_2](https://user-images.githubusercontent.com/107353865/194125098-c9d19668-7288-491d-9199-8540ae8f8e4e.png)

Тест:
![Тест_2](https://user-images.githubusercontent.com/107353865/194125113-b2a945e0-371e-4e4d-bdac-4c4c22ca53d8.png)
