### ISSUE TITLE
В классе GameStore, Метод containsGame, возвращает всегда false

### ISSUE THREAD

**Issue by idsaidov** [idsaidov/javaqa-team-project#4]
### Описание
После добавления игры в Store, метод containsGame в классе GameStore возвращает значение false. 

### Локация дефекта

https://github.com/idsaidov/javaqa-team-project/blob/e3ec7164146f35d3370ef8880a692690a81e14d9/src/main/java/ru/netology/GameStore.java#L32-L39

### Шаги воспроизведения

1. Открыть [код программы (ветке GameStore)](https://github.com/idsaidov/javaqa-team-project/tree/GameStore) в IDEA
2.  Открыть [GameStoreTest](https://github.com/idsaidov/javaqa-team-project/blob/GameStore/src/test/java/ru/netology/GameStoreTest.java) и запустить тест shouldAddGame
4. Посмотреть вывод на консоли

_Ожидаемый результат:_ Результат теста true

_Фактический результат:_ Результат теста false.

### Скриншот

![1](https://user-images.githubusercontent.com/107353865/193652668-5b76b97e-20a5-4e94-8eca-4c5614762fab.png)

### Окружение

**Операционная система**: Windows 10, **Версия**:  21H2
**IDE**: IntelliJ IDEA 2022.2 (Community Edition)
**Java**: OpenJDK 11

**Comment by birdperson913** [comment]
Проблема решена
