### ISSUE TITLE
В классе Gamestore не принимаются значение времени равное одному

### ISSUE THREAD

**Issue by idsaidov** [idsaidov/javaqa-team-project#5]
### Описание
В классе Gamestore метод getMostPlayer, не принимает значение времени равное одному

### Локация дефекта

https://github.com/idsaidov/javaqa-team-project/blob/b67ee0839d1e90ccd4b5572b7047f68cd794f6d9/src/main/java/ru/netology/GameStore.java#L58-L69

### Шаги воспроизведения

1. Открыть [код программы (ветке GameStore)](https://github.com/idsaidov/javaqa-team-project/tree/GameStore) в IDEA
2.  Открыть [GameStoreTest](https://github.com/idsaidov/javaqa-team-project/blob/GameStore/src/test/java/ru/netology/GameStoreTest.java) и запустить тест shouldGetMostPlayerEqualsZero
4. Посмотреть вывод на консоли

_Ожидаемый результат:_ Результат теста: метод getMostPlayer вернул значение имени игрока "Player9" и время добавилось. Тест пройден.

_Фактический результат:_ Результат теста: метод getMostPlayer не вернул значение имени игрока "Player9" и время не добавилось. Тест провален.

### Скриншот

![2](https://user-images.githubusercontent.com/107353865/193670122-fc8f27bc-5627-4d96-83f2-6c321cf9f86f.png)

### Окружение

**Операционная система**: Windows 10, **Версия**:  21H2
**IDE**: IntelliJ IDEA 2022.2 (Community Edition)
**Java**: OpenJDK 11

**Comment by birdperson913** [comment]
Проблема решена
