### ISSUE TITLE
В классе GameStore, сумма времени всех игроков не возвращается.

### ISSUE THREAD

**Issue by idsaidov** [idsaidov/javaqa-team-project#6]
### Описание

В классе GameStore, метод getSumPlayedTime, сумма времени всех игроков не возвращается.

### Локация дефекта

https://github.com/idsaidov/javaqa-team-project/blob/b67ee0839d1e90ccd4b5572b7047f68cd794f6d9/src/main/java/ru/netology/GameStore.java#L75-L78

### Шаги воспроизведения

1. Открыть [код программы (ветке GameStore)](https://github.com/idsaidov/javaqa-team-project/tree/GameStore) в IDEA
2.  Открыть [GameStoreTest](https://github.com/idsaidov/javaqa-team-project/blob/GameStore/src/test/java/ru/netology/GameStoreTest.java) и запустить тест shouldGetSumOnePlayedTime
4. Посмотреть вывод на консоли

_Ожидаемый результат:_ Результат теста: Время суммировалось, метод getSumPlayedTime показывает - 1. Тест проходит. 

_Фактический результат:_ Результат теста: Метод getSumPlayedTime показывает - 0. Тест провален.

### Скриншот

![3 (2)](https://user-images.githubusercontent.com/107353865/193674836-8db8b615-cbba-4a74-8e45-e0cb7bf53441.png)

### Окружение

**Операционная система**: Windows 10, **Версия**:  21H2
**IDE**: IntelliJ IDEA 2022.2 (Community Edition)
**Java**: OpenJDK 11

**Comment by birdperson913** [comment]
Проблема Решена

**Comment by birdperson913** [comment]
Задача закрыта

**Comment by birdperson913** [comment]
Проблема решена
